/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MntoBarra.java
 *
 * Created on 28-may-2010, 11:31:50
 */
package es.cvjpy.componentes;

import es.cvjpy.MngrCliPro;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.ComponentInputMap;
import javax.swing.InputMap;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.plaf.ActionMapUIResource;

/**
 *
 * @author CarlosVJ
 */
public class BqdaBarra extends javax.swing.JPanel {

    /**
     * Creates new form MntoBarra
     */
    public BqdaBarra() {
        initComponents();
        lasteclas();
    }

    private void lasteclas() {
        InputMap keyMap;
        ActionMap actionMap;

        Action escapeaction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                botonsalir();
            }
        };
        Action f3action = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                botonseleccionar();
            }
        };
        Action inicioaction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                botonprimero();
            }
        };
        Action repagaction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                botonanterior();
            }
        };
        Action avpagaction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                botonsiguiente();
            }
        };
        Action finaction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                botonultimo();
            }
        };


        keyMap = new ComponentInputMap(botonesc);
        keyMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escape");
        actionMap = new ActionMapUIResource();
        actionMap.put("escape", escapeaction);
        SwingUtilities.replaceUIActionMap(botonesc, actionMap);
        SwingUtilities.replaceUIInputMap(botonesc, JComponent.WHEN_IN_FOCUSED_WINDOW, keyMap);

        keyMap = new ComponentInputMap(botonF3);
        keyMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0), "f3");
        actionMap = new ActionMapUIResource();
        actionMap.put("f3", f3action);
        SwingUtilities.replaceUIActionMap(botonF3, actionMap);
        SwingUtilities.replaceUIInputMap(botonF3, JComponent.WHEN_IN_FOCUSED_WINDOW, keyMap);

        keyMap = new ComponentInputMap(botonprimero);
        keyMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_HOME, KeyEvent.CTRL_MASK), "inicio");
        actionMap = new ActionMapUIResource();
        actionMap.put("inicio", inicioaction);
        SwingUtilities.replaceUIActionMap(botonprimero, actionMap);
        SwingUtilities.replaceUIInputMap(botonprimero, JComponent.WHEN_IN_FOCUSED_WINDOW, keyMap);

        keyMap = new ComponentInputMap(botonanterior);
        keyMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_PAGE_UP, KeyEvent.CTRL_MASK), "repag");
        actionMap = new ActionMapUIResource();
        actionMap.put("repag", repagaction);
        SwingUtilities.replaceUIActionMap(botonanterior, actionMap);
        SwingUtilities.replaceUIInputMap(botonanterior, JComponent.WHEN_IN_FOCUSED_WINDOW, keyMap);

        keyMap = new ComponentInputMap(botonsiguiente);
        keyMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_PAGE_DOWN, KeyEvent.CTRL_MASK), "avpag");
        actionMap = new ActionMapUIResource();
        actionMap.put("avpag", avpagaction);
        SwingUtilities.replaceUIActionMap(botonsiguiente, actionMap);
        SwingUtilities.replaceUIInputMap(botonsiguiente, JComponent.WHEN_IN_FOCUSED_WINDOW, keyMap);

        keyMap = new ComponentInputMap(botonultimo);
        keyMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_END, KeyEvent.CTRL_MASK), "fin");
        actionMap = new ActionMapUIResource();
        actionMap.put("fin", finaction);
        SwingUtilities.replaceUIActionMap(botonultimo, actionMap);
        SwingUtilities.replaceUIInputMap(botonultimo, JComponent.WHEN_IN_FOCUSED_WINDOW, keyMap);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        teclasPanel = new javax.swing.JPanel();
        botonesc = new javax.swing.JButton();
        botonF3 = new javax.swing.JButton();
        navegarPanel = new javax.swing.JPanel();
        botonprimero = new javax.swing.JButton();
        botonanterior = new javax.swing.JButton();
        botonsiguiente = new javax.swing.JButton();
        botonultimo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();

        setFocusable(false);

        jPanel1.setFocusable(false);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("alfalit"); // NOI18N
        teclasPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("Accion"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10))); // NOI18N
        teclasPanel.setFocusable(false);
        teclasPanel.setOpaque(false);

        botonesc.setFont(botonesc.getFont().deriveFont((botonesc.getFont().getStyle() & ~java.awt.Font.ITALIC) & ~java.awt.Font.BOLD, botonesc.getFont().getSize()-2));
        botonesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/cvjpy/resources/Salir16.gif"))); // NOI18N
        botonesc.setText(bundle.getString("Esc")); // NOI18N
        botonesc.setActionCommand("ESC");
        botonesc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonesc.setFocusable(false);
        botonesc.setPreferredSize(new java.awt.Dimension(50, 25));
        botonesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonescActionPerformed(evt);
            }
        });
        teclasPanel.add(botonesc);

        botonF3.setFont(botonF3.getFont().deriveFont((botonF3.getFont().getStyle() & ~java.awt.Font.ITALIC) & ~java.awt.Font.BOLD, botonF3.getFont().getSize()-2));
        botonF3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/cvjpy/resources/Salva16.gif"))); // NOI18N
        botonF3.setText(bundle.getString("F3")); // NOI18N
        botonF3.setToolTipText(bundle.getString("Seleccionar")); // NOI18N
        botonF3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonF3.setFocusable(false);
        botonF3.setPreferredSize(new java.awt.Dimension(40, 25));
        botonF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonF3ActionPerformed(evt);
            }
        });
        teclasPanel.add(botonF3);

        jPanel1.add(teclasPanel);

        navegarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("Pagina"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10))); // NOI18N
        navegarPanel.setFocusable(false);
        navegarPanel.setOpaque(false);

        botonprimero.setFont(botonprimero.getFont().deriveFont((botonprimero.getFont().getStyle() & ~java.awt.Font.ITALIC) & ~java.awt.Font.BOLD, botonprimero.getFont().getSize()-2));
        botonprimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/cvjpy/resources/Primero.gif"))); // NOI18N
        botonprimero.setText(bundle.getString("Primera")); // NOI18N
        botonprimero.setToolTipText(bundle.getString("Pulse_Ctrl_Inicio")); // NOI18N
        botonprimero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonprimero.setFocusable(false);
        botonprimero.setPreferredSize(new java.awt.Dimension(75, 25));
        botonprimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonprimeroActionPerformed(evt);
            }
        });
        navegarPanel.add(botonprimero);

        botonanterior.setFont(botonanterior.getFont().deriveFont((botonanterior.getFont().getStyle() & ~java.awt.Font.ITALIC) & ~java.awt.Font.BOLD, botonanterior.getFont().getSize()-2));
        botonanterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/cvjpy/resources/Anterior.gif"))); // NOI18N
        botonanterior.setText(bundle.getString("Anterior")); // NOI18N
        botonanterior.setToolTipText(bundle.getString("Pulse_Ctrl_RePag")); // NOI18N
        botonanterior.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonanterior.setFocusable(false);
        botonanterior.setPreferredSize(new java.awt.Dimension(75, 25));
        botonanterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonanteriorActionPerformed(evt);
            }
        });
        navegarPanel.add(botonanterior);

        botonsiguiente.setFont(botonsiguiente.getFont().deriveFont((botonsiguiente.getFont().getStyle() & ~java.awt.Font.ITALIC) & ~java.awt.Font.BOLD, botonsiguiente.getFont().getSize()-2));
        botonsiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/cvjpy/resources/Siguiente.gif"))); // NOI18N
        botonsiguiente.setText(bundle.getString("Siguiente")); // NOI18N
        botonsiguiente.setToolTipText(bundle.getString("Pulse_Ctrl_AvPag")); // NOI18N
        botonsiguiente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonsiguiente.setFocusable(false);
        botonsiguiente.setPreferredSize(new java.awt.Dimension(75, 25));
        botonsiguiente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsiguienteActionPerformed(evt);
            }
        });
        navegarPanel.add(botonsiguiente);

        botonultimo.setFont(botonultimo.getFont().deriveFont((botonultimo.getFont().getStyle() & ~java.awt.Font.ITALIC) & ~java.awt.Font.BOLD, botonultimo.getFont().getSize()-2));
        botonultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/cvjpy/resources/Ultimo.gif"))); // NOI18N
        botonultimo.setText(bundle.getString("Ultima")); // NOI18N
        botonultimo.setToolTipText(bundle.getString("Pulse_Ctrl_Fin")); // NOI18N
        botonultimo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonultimo.setFocusable(false);
        botonultimo.setPreferredSize(new java.awt.Dimension(75, 25));
        botonultimo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonultimoActionPerformed(evt);
            }
        });
        navegarPanel.add(botonultimo);

        jPanel1.add(navegarPanel);

        jPanel2.setFocusable(false);

        jLabel3.setText(bundle.getString("Ordenar_por")); // NOI18N
        jLabel3.setFocusable(false);

        jLabel4.setText(bundle.getString("Buscar")); // NOI18N
        jLabel4.setFocusable(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setFocusable(false);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${datos.clasificaciones}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jComboBox1);
        bindingGroup.addBinding(jComboBoxBinding);
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${datos.clasificarPorSelected}"), jComboBox1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${datos.buscar}"), jTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField1CaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void botonescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonescActionPerformed
        botonsalir();
}//GEN-LAST:event_botonescActionPerformed

    private void botonF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonF3ActionPerformed
        botonseleccionar();
}//GEN-LAST:event_botonF3ActionPerformed

    private void botonprimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonprimeroActionPerformed
        botonprimero();
}//GEN-LAST:event_botonprimeroActionPerformed

    private void botonanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonanteriorActionPerformed
        botonanterior();
}//GEN-LAST:event_botonanteriorActionPerformed

    private void botonsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsiguienteActionPerformed
        botonsiguiente();
}//GEN-LAST:event_botonsiguienteActionPerformed

    private void botonultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonultimoActionPerformed
        botonultimo();
}//GEN-LAST:event_botonultimoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        if (trabajando) {
            getDatos().relista();
            botonprimero();
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField1CaretUpdate

        refresh();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                getDatos().relista();
                botonprimero();
            }
        });


    }//GEN-LAST:event_jTextField1CaretUpdate
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton botonF3;
    protected javax.swing.JButton botonanterior;
    protected javax.swing.JButton botonesc;
    protected javax.swing.JButton botonprimero;
    protected javax.swing.JButton botonsiguiente;
    protected javax.swing.JButton botonultimo;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel navegarPanel;
    private javax.swing.JPanel teclasPanel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private boolean trabajando = false;
    private MngrCliPro datos;
    public static final String PROP_DATOS = "datos";

    public MngrCliPro getDatos() {
        return datos;
    }

    public void setDatos(MngrCliPro datos) {
        trabajando = false;
        MngrCliPro oldDatos = this.datos;
        this.datos = datos;
        firePropertyChange(PROP_DATOS, oldDatos, datos);
        trabajando = true; //Los combobox disparan actionPerformed al contruir el componente, y no mola.
    }

    private void refresh() {
        firePropertyChange(PROP_DATOS, null, datos);
    }

    private void refreshLuego() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                refresh();
            }
        });
    }
    private List<ActionListener> escuchas;

    private List<ActionListener> getEscuchas() {
        if (escuchas == null) {
            escuchas = new ArrayList();
        }
        return escuchas;
    }

    public void addActionListener(ActionListener al) {
        this.getEscuchas().add(al);
    }

    public void removeActionListener(ActionListener al) {
        this.getEscuchas().remove(al);
    }

    public void removeActionListenerAll() {
        this.escuchas = null;
    }

    private void fireActionPerformed(JButton boton) {
        ActionEvent ae = new ActionEvent(boton, boton.hashCode(), boton.getActionCommand());
        for (ActionListener uno : getEscuchas()) {
            uno.actionPerformed(ae);
        }
    }

    private void botonsalir() {
        this.fireActionPerformed(botonesc);
    }

    public void botonseleccionar() {
        Cursor antcursor = getCursor();
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        getDatos().selecciona();
        fireActionPerformed(botonF3);
        setCursor(antcursor);
    }

    private void botonprimero() {
        Cursor antcursor = getCursor();
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        getDatos().paginaPrimera();
        fireActionPerformed(botonprimero);
        setCursor(antcursor);
    }

    private void botonanterior() {
        Cursor antcursor = getCursor();
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        getDatos().paginaAnterior();
        fireActionPerformed(botonanterior);
        setCursor(antcursor);
    }

    private void botonsiguiente() {
        Cursor antcursor = getCursor();
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        getDatos().paginaSiguiente();
        fireActionPerformed(botonsiguiente);
        setCursor(antcursor);
    }

    private void botonultimo() {
        Cursor antcursor = getCursor();
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        getDatos().paginaUltima();
        fireActionPerformed(botonultimo);
        setCursor(antcursor);
    }

    public boolean isEscape() {
        return botonesc.isVisible();
    }

    public void setEscape(boolean flag) {
        botonesc.setVisible(flag);
    }

    public boolean isF3() {
        return botonF3.isVisible();
    }

    public void setF3(boolean flag) {
        botonF3.setVisible(flag);
    }

    public boolean isNavegable() {
        return navegarPanel.isVisible();
    }

    public void setNavegable(boolean flag) {
        navegarPanel.setVisible(flag);
    }

    public boolean isPrimerable() {
        return botonprimero.isVisible();
    }

    public void setPrimerable(boolean flag) {
        botonprimero.setVisible(flag);
    }

    public boolean isUltimable() {
        return botonultimo.isVisible();
    }

    public void setUltimable(boolean flag) {
        botonultimo.setVisible(flag);
    }

    public String getTextF3() {
        return botonF3.getToolTipText();
    }

    public void setTextF3(String text) {
        botonF3.setToolTipText(text);
    }

    public boolean isEnabledF3() {
        return botonF3.isEnabled();
    }

    public void setEnabledF3(boolean siono) {
        botonF3.setEnabled(siono);
    }
}
